import { createFileRoute, Link } from "@tanstack/react-router";
import { AppShell } from "@/components/shell/AppShell";
import { useAuth } from "@/lib/auth";
import { levelProgress, rankForLevel } from "@/lib/gamification";
import { useAchievements, useMissions } from "@/lib/queries";
import { AvatarCanvas } from "@/components/avatar/AvatarCanvas";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
export const Route=createFileRoute("/profile")({component:ProfilePage});
function ProfilePage(){const{profile,user,isAdmin,signOut}=useAuth();const{data:missions}=useMissions(profile?.user_id);const{data:achievements}=useAchievements(profile?.user_id);const prog=levelProgress(profile?.xp??0);const rank=rankForLevel(prog.level);return <AppShell title="You" subtitle={rank.name}><section className="surface-glass rounded-3xl p-5 text-center"><AvatarCanvas config={profile?.avatar_config??null} size={104} mood="celebrate" className="mx-auto rounded-3xl ring-2 ring-gold/40"/><h2 className="mt-3 font-display text-xl font-semibold">{profile?.display_name??"User"}</h2><p className="text-xs text-muted-foreground">Level {prog.level} · {(profile?.xp??0).toLocaleString()} XP · {profile?.streak??0} day streak</p><Progress value={prog.percent} className="mt-4 h-2"/>{user&&isAdmin&&<Button asChild className="press mt-4 w-full rounded-2xl"><Link to="/admin">Open admin</Link></Button>}{user&&<Button variant="outline" className="press mt-4 w-full rounded-2xl" onClick={()=>void signOut()}>Sign out</Button>}</section><section className="mt-6"><h3 className="font-display text-lg font-semibold">Missions</h3><div className="mt-3 space-y-2.5">{(missions??[]).map(m=><div key={m.id} className="surface-glass rounded-2xl p-3.5"><div className="flex items-center justify-between gap-3"><p className="truncate text-sm font-semibold">{m.title}</p><span className="shrink-0 text-[11px] font-bold text-gold-foreground">+{m.xp_reward} XP</span></div><Progress value={Math.min(100,Math.round(((m.progress??0)/m.target)*100))} className="mt-2 h-1.5"/></div>)}</div></section><section className="mt-6"><h3 className="font-display text-lg font-semibold">Achievements</h3><div className="mt-3 grid grid-cols-3 gap-2.5">{(achievements??[]).map(a=><div key={a.id} className={"rounded-2xl border p-3 text-center "+(a.earned?"border-gold/40 bg-gold/10":"border-border opacity-60")}><p className="text-2xl">{a.earned?"🏅":"🔒"}</p><p className="mt-1 text-[11px] font-semibold leading-tight">{a.title}</p></div>)}</div></section></AppShell>}
